name: bitcoin_bip32
version: 0.1.2
description: Library implementing Bitcoins BIP32 (Hierarchical Deterministic key derivation) specification in a Flutter friendly fashion.
author: Kolibri POS authors <info@kolibripos.com>
homepage: https://github.com/Kolibri-POS/bitcoin_bip32
environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  pointycastle:
    git:
      url: https://github.com/jungsoo827/pointycastle.git
      ref: master
  base58check: ^1.0.1
  convert: ^2.1.0

dev_dependencies:
  test: ^1.5.1

